preload = /home/mwilly/Pictures/Wallpapers/WishYouWereHere.png

wallpaper {
    monitor=DP-3
    path=/home/mwilly/Pictures/Wallpapers/WishYouWereHere.png
}
wallpaper {
    monitor=HDMI-A-1
    path=/home/mwilly/Pictures/Wallpapers/WishYouWereHere.png
}
splash=false